name = "sougoushinricheck"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[vars]
PUBLIC_BASE_URL = "https://sougoushinricheck.pages.dev"

# These should be set as secrets in Cloudflare dashboard
# TURSO_DATABASE_URL = ""
# TURSO_AUTH_TOKEN = ""
